@startuml
!includeurl https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/cerulean/puml-theme-cerulean.puml

entity User {
  +id
  --
  ~username
  ~password
  ~firstName
  ~lastName
  --
  #roleId
}

entity System {
  +id
  --
  ~name
  ~street
  ~city
  ~zip
  --
  #customerId
}

entity Maintenance {
  +id
  --
  ~name
  ~frequency
  ~start_date
  --
  #systemId
  #userId
}

entity Customer {
  +id
  --
  ~name
  ~street
  ~city
  ~zip
  ~email
  ~contactperson
  ~phone
}

entity State {
  +id
  --
  ~name
}

entity Role {
  +id
  --
  ~name
}

entity Appointment {
  +id
  --
  ~date
  --
  #maintenanceId
  #stateId
}

Customer -right-{ System
System -right-{ Maintenance
Appointment }-- State
User }-right- Role
User -left-{ Maintenance
Maintenance -down-{ Appointment
  
@enduml
